In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
pd.read_csv('ex2.csv',header = None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
pd.read_csv('ex2.csv',names = ['a','b','c','d','message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
names = ['a','b','c','d','message']

In [7]:
pd.read_csv('ex2.csv',names =names, index_col = 'message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [8]:
parsed = pd.read_csv("data/csv_mindex.csv",
                     index_col=["key1", "key2"])

In [10]:
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [11]:
result = pd.read_csv("data/ex3.txt", sep=r"\s+")
result
# a separator (what divides the column in the file)
# r"\s+" is a regular expression   ,\s means any whitespace character,+ means one or more accurance

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [12]:
result.columns

Index(['A', 'B', 'C'], dtype='object')

In [13]:
pd.read_csv('data/ex4.csv',skiprows = [0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [14]:
result = pd.read_csv("data/ex5.csv")
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [16]:
pd.isna(result)
#isna() checks the value is missing or not in a dataFrame
# if its missing it returns true
# if not it returns false

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [17]:
result = pd.read_csv("data/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [20]:
result2 = pd.read_csv("data/ex5.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [21]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

# Reading Text Files in Pieces

In [22]:
pd.options.display.max_rows = 8
result = pd.read_csv("data/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
...        ...       ...       ...       ...  ..
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [23]:
result.describe()

                one           two         three          four
count  10000.000000  10000.000000  10000.000000  10000.000000
mean       0.045750      0.000871     -0.026463      0.015985
std        0.948825      1.003829      1.037273      0.982409
min       -3.726864     -3.465356     -3.234391     -3.173509
25%       -0.618617     -0.706643     -0.727791     -0.676291
50%        0.041638      0.018972     -0.032340     -0.005338
75%        0.701536      0.708405      0.626904      0.659369
max        2.833891      2.946737      3.053345      3.412734

In [25]:
chunker = pd.read_csv('data/ex6.csv',chunksize = 1500)
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [27]:
tot = pd.Series([], dtype='int64')
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)
tot[:8]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
dtype: float64

In [29]:
tot

key
E    368.0
X    364.0
L    346.0
O    343.0
     ...
2    152.0
0    151.0
9    150.0
1    146.0
Length: 36, dtype: float64

# Writing data to text format

In [31]:
data = pd.read_csv("data/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [32]:
data.to_csv('data/out5.csv')

In [33]:
import sys
data.to_csv(sys.stdout, sep = "|")
# Pandas can read csv file with a single-character delimeter
# We can use csv module to read other csv files

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [34]:
import csv
f = open("data/ex7.csv")
reader = csv.reader(f)
for line in reader:
    print(line)
f.close()

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [35]:
with open("data/ex7.csv") as f:
    lines = list(csv.reader(f))
print(lines)

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [36]:
header, values = lines[0], lines[1:]

In [37]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [38]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [39]:
df = pd.DataFrame(data_dict)
df

   a  b  c
0  1  2  3
1  1  2  3

# JSON Data

In [40]:
import pandas as pd
import numpy as np
import json 
import sys

In [41]:
obj = """
{"name": "Wes",
"cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
"pet": null,
"siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
{"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

In [42]:
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [45]:
asjson = json.dumps(result)
asjson

#json.dumps ---> tries to convert into JSON text
#asjson ---> stores the JSON  string

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [46]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

In [48]:
data = pd.read_json("data/example.json")
data

# this converts json into a dataframe

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [49]:
data.to_json(sys.stdout)
# this converts DataFrame into json

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [50]:
tables = pd.read_html("data/fdic_failed_bank_list.html")

In [51]:
len(tables)

1

In [52]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [53]:
close_timestamps = pd.to_datetime(failures['Closing Date'])

In [56]:
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
       ...
2001      4
2007      3
2003      3
2000      2
Name: count, Length: 15, dtype: int64

# Parsing XML with lxml.objectify

In [58]:
from lxml import objectify

In [59]:
path = "data/Performance_MNR.xml"
with open(path) as f:
    parsed = objectify.parse(f)
root = parsed.getroot()

In [60]:
data = []
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
               "DESIRED_CHANGE", "DECIMAL_PLACES"]
for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

In [61]:
perf = pd.DataFrame(data)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [62]:
perf2 = pd.read_xml(path)
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

# Binary Data Formats

In [63]:
frame = pd.read_csv("data/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [64]:
# Save frame as python pickle format
frame.to_pickle("data/frame.pkl")

# Reading Microsoft Excel Files

In [65]:
xldata = pd.ExcelFile("data/ex1.xlsx")
xldata.sheet_names

['Sheet1']

In [66]:
xldata.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [67]:
xldata.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

# Interacting with web APIs

In [68]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
resp

In [69]:
data = resp.json()
print(data[0]['url'])
print(data[0]['title'])

https://api.github.com/repos/pandas-dev/pandas/issues/64592
BUG: concat with datetime64 columns of differing resolutions results ...

In [70]:
issues = pd.DataFrame(data, columns=["number", "title",
                                     "labels", "state"])
issues.head()

,number,title,labels,state
0,64592,BUG: concat with datetime64 columns of differi...,[],open
1,64590,PERF: pass string path to PyArrow in read_parq...,[],open
2,64589,DEPR: deprecate non-ndarray/Series/Index x in ...,[],open
3,64588,ENH: pd.interpolate() add skip interpolation w...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
4,64587,TST: Add regression test for GH#55969,[],open

# Interacting with DataBase

In [71]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER);
"""

In [72]:
con = sqlite3.connect("mydata.sqlite")
con.execute(query)

In [73]:
data = [("Atlanta", "Georgia", 1.25, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)

In [74]:
con.commit()

In [75]:
cursor = con.execute("SELECT * FROM test")
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [76]:
import sqlalchemy as sqla
db = sqla.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5